### ISSUE TITLE
Feature request - open in right side panel on Shift+Click

### ISSUE THREAD

**Issue by myownstandard** [sethyuan/logseq-plugin-tocgen#10]
It would be great! Thank you!

**Comment by sethyuan** [comment]
You can shift click on the bullet right now to have it opened in the right sidebar. I'll look if I can make this behavior for the TOC itself later.

**Comment by sethyuan** [comment]
@myownstandard It's implemented, please give new version a try.

**Comment by nhan000** [comment]
If I click on the first line of the TOC, it opens the TOC block on the right sidebar.
If I click on the content of the TOC, it is opened in the main window. I'd expect (and would like) this behavior where the clicked content is opened in the ride sidebar instead of above since I can just shift click the bullet to open the TOC block on the right sidebar?

**Comment by sethyuan** [comment]
Good point. So the desired behavior would be this:

- Shift clicking the bullet or selecting from the block's context menu will open the TOC in the right sidebar.
- Shift clicking on items on the TOC will open that item's block in the right sidebar.

**Comment by sethyuan** [comment]
Done. Can you give it a try?

**Comment by nhan000** [comment]
works great! Thanks a lot!
