### ISSUE TITLE
page link don't work until loaded because of lazy loading

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [sethyuan/logseq-plugin-tocgen#31]
Hi,

Let me quote the previous message from #7 

I said : 
> I ported a very long .docx file to .md and your plugin is incredible to access it. I'm currently on 0.6.7 and found a quite serious bug : `page` links only work if the document has been loaded in RAM apparently.
> 
> To be a bit more clear, after putting the toc in the sidebar, to make the `page`links work I need to scroll down in the document until SECTION (so it's now "loaded") and only then can I use the SECTION `page` links. Otherwise, clicking does nothing and I see no new output in the terminal window running "flatpak run logseq".
> 
> The problem is then that it renders your incredible plugin useless to me : going to the end of the document takes forever for a long document and I have to redo it again if I changed document even once.
> 
> Is there a way to load the whole page direclty and make sure the `page` links work?
> 
> Thanks a lot!

@sethyuan  answered:

> Since this is an old plugin SDK problem, I ran another test with the newest version of Logseq and the plugin SDK, and the result is the same, it can't automatically load the necessary content.
> 
> The lazy loading behavior of the page by Logseq is to help with loading performance, it only loads as you scroll down the page. However this introduced the issue you mentioned for the plugin SDK's "goto" function.
> 
> There is no good solutions on the plugin side, it must be solved by the plugin SDK, which is maintained by the Logseq team.

============= Now : 
Thanks for the quick answer and the clear explanation!

I don't really understand how lazy loading can imper the "goto" feature. The goto feature should load the location and go to it, if it has to be loaded already then you're "already there / don't need to go". Hence, if you don't mind me asking, are you certain this is a feature and not a bug ?

I don't feel legitimate to go ask the logseq team about it as I have for now a very limited understanding of the SDK :/

**Comment by sethyuan** [comment]
OK, so you want to go technical.

- The "goto" functionality is provided by the Logseq plugin SDK. tocgen uses the SDK to jump.
- The plugin SDK is maintained by the Logseq team.
- The "goto" functionality has unwanted behavior when a page is too long.

Solution to it: report this issue to the Logseq team.

Is this clear?

All I can do is also report this to the Logseq team, which I did several versions ago. Sadly, the SDK's behavior remained unchanged all this time. Maybe if more users were to report the same problem, the team might notice its importance, which is why I suggest you go and make a report to the Logseq team.
