### ISSUE TITLE
Translations: Error 404 in console

### ISSUE THREAD

**Issue by yoyurec** [sethyuan/logseq-plugin-tocgen#39]
Plugin trys to get unexesting translation:
`index.c8f77771.js:21 GET https://raw.githubusercontent.com/sethyuan/logseq-plugin-tocgen/master/src/translations/en-US.json 404`

**Comment by sethyuan** [comment]
It's by design. The l10n library will try to load a remote translation if no builtin translation is found. If no remote translation is found neither, it will fallback to use the default translation, which is usually English.

The builtin locale is "en" and yours is "en-US", hence it triggered a remote loading attempt. You can safely ignore it, this is only called once when the plugin is first loaded.

**Comment by yoyurec** [comment]
understand, tnx
